version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: electron
    versions:
    - 11.2.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
  - dependency-name: stylelint
    versions:
    - 13.9.0
