import {
  faCalculator,
  faFlask,
  faCode,
  faCalendarAlt,
  faCoins,
  faRulerCombined,
  faBolt,
  faVectorSquare,
  faHdd,
  faThLarge,
  faBurn,
  faDotCircle,
  faLightbulb,
  faRuler,
  faWeightHanging,
  faWalking,
  faTh,
  faAtom,
  faBatteryFull,
  faTachometerAlt,
  faThermometerQuarter,
  faClock,
  faCube,
  faCompress,
  faCarBattery,
  faPlug,
  faStream
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  basic: faCalculator,
  scientific: faFlask,
  programmer: faCode,
  date: faCalendarAlt,
  currency: faCoins,
  angle: faRulerCombined,
  apparentpower: faPlug,
  area: faVectorSquare,
  current: faCarBattery,
  digital: faHdd,
  each: faThLarge,
  energy: faBurn,
  frequency: faDotCircle,
  illuminance: faLightbulb,
  length: faRuler,
  mass: faWeightHanging,
  pace: faWalking,
  partsper: faTh,
  power: faBatteryFull,
  pressure: faCompress,
  reactiveenergy: faAtom,
  reactivepower: faBatteryFull,
  speed: faTachometerAlt,
  temperature: faThermometerQuarter,
  time: faClock,
  voltage: faBolt,
  volume: faCube,
  volumeflowrate: faStream
};
